import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import profilePic from '../public/Artwork10.JPEG';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Ishan's EPK</h1>
        <Image
          src={profilePic}
          alt='Picture of the author'
          width={500}
          height={500}
          blurDataURL='data:...'
          placeholder='blur' // Optional blur-up while loading
        />
      </main>
    </>
  );
}
