import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import NavHome from '@/components/NavHome';
import { motion } from 'framer-motion';
import { Link } from '@nextui-org/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ishan Electronic Press Kit</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='shortcut icon' href='./icon.png' />
      </Head>
      <main>
        <div className=''>
          <NavHome Home={'underline'} About={''} Press={''} Media={''} />
        </div>
        <div className=''></div>
      </main>
    </>
  );
}
